{
  "formatVersion": "1.1",
  "component": {
    "group": "app.convokit",
    "module": "convokit-android-ui",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "app.convokit",
          "module": "convokit-android",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "convokit-android-ui-0.6.0.aar",
          "url": "convokit-android-ui-0.6.0.aar",
          "size": 373681,
          "sha512": "6d19b53b223826f7da76b9b61e2ddcc4befea9ffa9afc62fd388f9a53afa941fc288251b53df636cce7303a2dfd1be991752f5acfea4cd8e6abbfdd6db4367d0",
          "sha256": "3bf3b7755fa3406775160447543b8e032ed406eace842e1498063d560c8d96a3",
          "sha1": "8ce2cfe4c9b561bdfe6d4d94c9e49e64ef7ed56b",
          "md5": "707f0b94144954860d1a16137d0e572b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "app.convokit",
          "module": "convokit-android",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "convokit-android-ui-0.6.0.aar",
          "url": "convokit-android-ui-0.6.0.aar",
          "size": 373681,
          "sha512": "6d19b53b223826f7da76b9b61e2ddcc4befea9ffa9afc62fd388f9a53afa941fc288251b53df636cce7303a2dfd1be991752f5acfea4cd8e6abbfdd6db4367d0",
          "sha256": "3bf3b7755fa3406775160447543b8e032ed406eace842e1498063d560c8d96a3",
          "sha1": "8ce2cfe4c9b561bdfe6d4d94c9e49e64ef7ed56b",
          "md5": "707f0b94144954860d1a16137d0e572b"
        }
      ]
    }
  ]
}
