{
  "formatVersion": "1.1",
  "component": {
    "group": "app.convokit",
    "module": "convokit-android-ui",
    "version": "0.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "app.convokit",
          "module": "convokit-android",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "convokit-android-ui-0.10.0.aar",
          "url": "convokit-android-ui-0.10.0.aar",
          "size": 605232,
          "sha512": "5bf54e5c8c39597a6780af6a7ff0d743f6a25fae7121a26cdb02c7a7346c83edd1d65cb0b3a62d421849190831f3446a724e6433610cdfa505882b96e110e2ff",
          "sha256": "6541c49954f0e121c7b9c30e51a62bdf0d70e08a8ea7ac308acb5db70314293d",
          "sha1": "e4c6fdd5479cb606a53c8a4248a79ec6de046339",
          "md5": "44bdd685f8ecd225cf74b899dc1a2d93"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "app.convokit",
          "module": "convokit-android",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "convokit-android-ui-0.10.0.aar",
          "url": "convokit-android-ui-0.10.0.aar",
          "size": 605232,
          "sha512": "5bf54e5c8c39597a6780af6a7ff0d743f6a25fae7121a26cdb02c7a7346c83edd1d65cb0b3a62d421849190831f3446a724e6433610cdfa505882b96e110e2ff",
          "sha256": "6541c49954f0e121c7b9c30e51a62bdf0d70e08a8ea7ac308acb5db70314293d",
          "sha1": "e4c6fdd5479cb606a53c8a4248a79ec6de046339",
          "md5": "44bdd685f8ecd225cf74b899dc1a2d93"
        }
      ]
    }
  ]
}
