{
  "formatVersion": "1.1",
  "component": {
    "group": "app.convokit",
    "module": "convokit-android",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "convokit-android-0.3.0.aar",
          "url": "convokit-android-0.3.0.aar",
          "size": 240283,
          "sha512": "f3b87b513dc0cd094a68a29cabcf7eac02013222285b8a97de8edd708d483fbc06ebe8400a84d4fc8fb4b8ac092da77afe793d0ca082954a1d317dd817ce8b8d",
          "sha256": "8f309d5d9743016ef81ccd790a89e25cc1d06a40e49ba7569c33265f1ca2a658",
          "sha1": "ed0458c1e35145bcf1a028249031b38cfada6833",
          "md5": "4074970f8469f7dff30b509fe533803b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.jan-tennert.supabase",
          "module": "realtime-kt",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "convokit-android-0.3.0.aar",
          "url": "convokit-android-0.3.0.aar",
          "size": 240283,
          "sha512": "f3b87b513dc0cd094a68a29cabcf7eac02013222285b8a97de8edd708d483fbc06ebe8400a84d4fc8fb4b8ac092da77afe793d0ca082954a1d317dd817ce8b8d",
          "sha256": "8f309d5d9743016ef81ccd790a89e25cc1d06a40e49ba7569c33265f1ca2a658",
          "sha1": "ed0458c1e35145bcf1a028249031b38cfada6833",
          "md5": "4074970f8469f7dff30b509fe533803b"
        }
      ]
    }
  ]
}
