{
  "formatVersion": "1.1",
  "component": {
    "group": "app.convokit",
    "module": "convokit-android-ui",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "app.convokit",
          "module": "convokit-android",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "convokit-android-ui-0.3.0.aar",
          "url": "convokit-android-ui-0.3.0.aar",
          "size": 309252,
          "sha512": "6cabe9855e3fdbeec77322e1c8fc2e708f4e441ee4f0bcd60c1a0f7bd00874971513c9b18812ec05f83ecde6896d3889d3c2ead15bed9e1b073acdbf91de813c",
          "sha256": "3ae83e1c099ac43e95510c117abe58d3d6599d5e61c1c56bf333449fe5207798",
          "sha1": "7d84bc4d6cb7c6faaeee10e501109f85cd79f7b5",
          "md5": "e89d1b8787a8af8b85dc348524613f0a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "app.convokit",
          "module": "convokit-android",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "convokit-android-ui-0.3.0.aar",
          "url": "convokit-android-ui-0.3.0.aar",
          "size": 309252,
          "sha512": "6cabe9855e3fdbeec77322e1c8fc2e708f4e441ee4f0bcd60c1a0f7bd00874971513c9b18812ec05f83ecde6896d3889d3c2ead15bed9e1b073acdbf91de813c",
          "sha256": "3ae83e1c099ac43e95510c117abe58d3d6599d5e61c1c56bf333449fe5207798",
          "sha1": "7d84bc4d6cb7c6faaeee10e501109f85cd79f7b5",
          "md5": "e89d1b8787a8af8b85dc348524613f0a"
        }
      ]
    }
  ]
}
