{
  "formatVersion": "1.1",
  "component": {
    "group": "app.convokit",
    "module": "convokit-android-ui",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "app.convokit",
          "module": "convokit-android",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "convokit-android-ui-0.2.0.aar",
          "url": "convokit-android-ui-0.2.0.aar",
          "size": 250213,
          "sha512": "998335aec22c6fb6f0c410330a556f38abbcc7b1ade07e9fd093eeb8c3ac8467ab6de2cdf804b132a9edca0eed74711344cfddee5c0d304838f324521c137cb3",
          "sha256": "ceeac6b924317cc28d8f6a1ed0e3a7dfac2ce327dbfebede3b130dbe2282771a",
          "sha1": "557cc915c6990bc18df01d4d6206e8fe8c6b4683",
          "md5": "2af1e29d7d7a058ff48c85d9153fe7be"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "app.convokit",
          "module": "convokit-android",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "convokit-android-ui-0.2.0.aar",
          "url": "convokit-android-ui-0.2.0.aar",
          "size": 250213,
          "sha512": "998335aec22c6fb6f0c410330a556f38abbcc7b1ade07e9fd093eeb8c3ac8467ab6de2cdf804b132a9edca0eed74711344cfddee5c0d304838f324521c137cb3",
          "sha256": "ceeac6b924317cc28d8f6a1ed0e3a7dfac2ce327dbfebede3b130dbe2282771a",
          "sha1": "557cc915c6990bc18df01d4d6206e8fe8c6b4683",
          "md5": "2af1e29d7d7a058ff48c85d9153fe7be"
        }
      ]
    }
  ]
}
