{
  "formatVersion": "1.1",
  "component": {
    "group": "app.convokit",
    "module": "convokit-android-ui",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "app.convokit",
          "module": "convokit-android",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "convokit-android-ui-0.2.1.aar",
          "url": "convokit-android-ui-0.2.1.aar",
          "size": 253230,
          "sha512": "67d3188f889ef111c331103e443ceb6fcc889935d5e080fd6ba9b186a279c5e0f0ff5188a08a6dc8f342244f7daf212e57c8415d360646f30c0cb6760f2f1dea",
          "sha256": "6497d44b04bc7c8cf8470905da18eef0902997fa3a55b4ff6d9bd0a826049080",
          "sha1": "07791bb601059e63d14d1f152880e7d76229c6aa",
          "md5": "d9481760a441fa956384eff7521c8ce1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "app.convokit",
          "module": "convokit-android",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "convokit-android-ui-0.2.1.aar",
          "url": "convokit-android-ui-0.2.1.aar",
          "size": 253230,
          "sha512": "67d3188f889ef111c331103e443ceb6fcc889935d5e080fd6ba9b186a279c5e0f0ff5188a08a6dc8f342244f7daf212e57c8415d360646f30c0cb6760f2f1dea",
          "sha256": "6497d44b04bc7c8cf8470905da18eef0902997fa3a55b4ff6d9bd0a826049080",
          "sha1": "07791bb601059e63d14d1f152880e7d76229c6aa",
          "md5": "d9481760a441fa956384eff7521c8ce1"
        }
      ]
    }
  ]
}
