{
  "formatVersion": "1.1",
  "component": {
    "group": "app.convokit",
    "module": "convokit-android-ui",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "app.convokit",
          "module": "convokit-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "convokit-android-ui-0.5.0.aar",
          "url": "convokit-android-ui-0.5.0.aar",
          "size": 345692,
          "sha512": "48a3971595c38f2c76f164081589626c7c3f1f34068f6a5ded45c1f5474e0934678fcb30698fc238f43a174f0acf6e7b380134228aba2e6f94e4a04c1e72de19",
          "sha256": "3a024cd948fd32a626be8efcfed4fd69f4012bd67e86d0941dda5270f771f510",
          "sha1": "f6d6e2940aebd4a7bd81aa9d550a6a02c21d961d",
          "md5": "9f2e5ed10a9ad0c69063d56ac4c3ef01"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "app.convokit",
          "module": "convokit-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "convokit-android-ui-0.5.0.aar",
          "url": "convokit-android-ui-0.5.0.aar",
          "size": 345692,
          "sha512": "48a3971595c38f2c76f164081589626c7c3f1f34068f6a5ded45c1f5474e0934678fcb30698fc238f43a174f0acf6e7b380134228aba2e6f94e4a04c1e72de19",
          "sha256": "3a024cd948fd32a626be8efcfed4fd69f4012bd67e86d0941dda5270f771f510",
          "sha1": "f6d6e2940aebd4a7bd81aa9d550a6a02c21d961d",
          "md5": "9f2e5ed10a9ad0c69063d56ac4c3ef01"
        }
      ]
    }
  ]
}
