{
  "formatVersion": "1.1",
  "component": {
    "group": "app.convokit",
    "module": "convokit-android-ui",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "app.convokit",
          "module": "convokit-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "convokit-android-ui-0.1.1.aar",
          "url": "convokit-android-ui-0.1.1.aar",
          "size": 250215,
          "sha512": "65d811b7d78755e9367cd5c71e308bc2666c4159985adc3d226c4f05f344b960a64dcfdac3b63b06be5f03bcbf277d48cf588c23160612b4120b8148504ef2aa",
          "sha256": "97949d52cf1a60efcc4f9656bea61e3dfcd38967e352e01c7ec42207978882d4",
          "sha1": "4566e28e2c30df70fd00006aaa27d71af6cecb9b",
          "md5": "075b59cd803b9af88e2ffc080e7e2935"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "app.convokit",
          "module": "convokit-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.05.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "convokit-android-ui-0.1.1.aar",
          "url": "convokit-android-ui-0.1.1.aar",
          "size": 250215,
          "sha512": "65d811b7d78755e9367cd5c71e308bc2666c4159985adc3d226c4f05f344b960a64dcfdac3b63b06be5f03bcbf277d48cf588c23160612b4120b8148504ef2aa",
          "sha256": "97949d52cf1a60efcc4f9656bea61e3dfcd38967e352e01c7ec42207978882d4",
          "sha1": "4566e28e2c30df70fd00006aaa27d71af6cecb9b",
          "md5": "075b59cd803b9af88e2ffc080e7e2935"
        }
      ]
    }
  ]
}
