{
  "formatVersion": "1.1",
  "component": {
    "group": "app.convokit",
    "module": "convokit-android",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "convokit-android-0.5.0.aar",
          "url": "convokit-android-0.5.0.aar",
          "size": 257522,
          "sha512": "e0d7700acebfeded00e025cafbc18979da43aa01cdd665879e9ee0d15213a3482fc55f549b0024c58aad06cae2f9a2d7f67a41a8805a6542ae3638127867d383",
          "sha256": "cb059fafab5f9f75f1849b73f2f532602d640341bcc749b0990938fb3378f481",
          "sha1": "67c113d0f17c463fce569aadabb43de8b509b6e4",
          "md5": "12814a6388ea9486702c6e64103ad019"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.jan-tennert.supabase",
          "module": "realtime-kt",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "convokit-android-0.5.0.aar",
          "url": "convokit-android-0.5.0.aar",
          "size": 257522,
          "sha512": "e0d7700acebfeded00e025cafbc18979da43aa01cdd665879e9ee0d15213a3482fc55f549b0024c58aad06cae2f9a2d7f67a41a8805a6542ae3638127867d383",
          "sha256": "cb059fafab5f9f75f1849b73f2f532602d640341bcc749b0990938fb3378f481",
          "sha1": "67c113d0f17c463fce569aadabb43de8b509b6e4",
          "md5": "12814a6388ea9486702c6e64103ad019"
        }
      ]
    }
  ]
}
