{
  "formatVersion": "1.1",
  "component": {
    "group": "app.convokit",
    "module": "convokit-android",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "convokit-android-0.9.0.aar",
          "url": "convokit-android-0.9.0.aar",
          "size": 293935,
          "sha512": "6ac64ee5ee636176b3dedb74a88884bbf1648ac75b1e07419ded5bffa2a7e7ac2156c0b91314ccbd906088b3e79fea4c00001cac5b5b18b7f4b93d93ba31aaaa",
          "sha256": "62c2f9e2a383453f963aae460d85017b95157cfc9525914cc6a46365e074471f",
          "sha1": "a8fe99d03bfca0cd6fdbf1345aa65e4e4a0e90b8",
          "md5": "d61bc876c43e94008825bb81203d037e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.jan-tennert.supabase",
          "module": "realtime-kt",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "convokit-android-0.9.0.aar",
          "url": "convokit-android-0.9.0.aar",
          "size": 293935,
          "sha512": "6ac64ee5ee636176b3dedb74a88884bbf1648ac75b1e07419ded5bffa2a7e7ac2156c0b91314ccbd906088b3e79fea4c00001cac5b5b18b7f4b93d93ba31aaaa",
          "sha256": "62c2f9e2a383453f963aae460d85017b95157cfc9525914cc6a46365e074471f",
          "sha1": "a8fe99d03bfca0cd6fdbf1345aa65e4e4a0e90b8",
          "md5": "d61bc876c43e94008825bb81203d037e"
        }
      ]
    }
  ]
}
