{
  "formatVersion": "1.1",
  "component": {
    "group": "app.convokit",
    "module": "convokit-android",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "convokit-android-0.7.0.aar",
          "url": "convokit-android-0.7.0.aar",
          "size": 282118,
          "sha512": "11fed98412014a5d884ecb7bd61a23c0c4e6699acc7d4d87df346d0913f5c5d37e256f7e6b7f44ef386567ca8cacae8e3ffb8a8292cc4928b887747da6a38e7e",
          "sha256": "db29bfa771e2efe51e427a2f995d1c0207285cc06226290dfe4f5084ca71b819",
          "sha1": "61a8f299a58f2eb675f247f49ad9a99973c65144",
          "md5": "4db1f898cf69b02ea255b7ea5e497cfe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.jan-tennert.supabase",
          "module": "realtime-kt",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "convokit-android-0.7.0.aar",
          "url": "convokit-android-0.7.0.aar",
          "size": 282118,
          "sha512": "11fed98412014a5d884ecb7bd61a23c0c4e6699acc7d4d87df346d0913f5c5d37e256f7e6b7f44ef386567ca8cacae8e3ffb8a8292cc4928b887747da6a38e7e",
          "sha256": "db29bfa771e2efe51e427a2f995d1c0207285cc06226290dfe4f5084ca71b819",
          "sha1": "61a8f299a58f2eb675f247f49ad9a99973c65144",
          "md5": "4db1f898cf69b02ea255b7ea5e497cfe"
        }
      ]
    }
  ]
}
